AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Sample API for Aizon solutions.

Parameters:
  Environment:
    Description: Environment prefixed to resource names
    Type: String

Resources:

Outputs:
